SERVICE_NUMBER = "#login-service-number-et"
PASSWORD = "#login-password-et"
SIGN_IN_BUTTON = "button.w-100:nth-child(4)"
DAYS_LEFT = ".mr-auto"
CONSUMED_UNITS = ".usage-details"
REMAINING_UNITS = ".remaining-details"
