SERVICE_NUMBER = "#login-service-number-et"
SERVICE_TYPE = "p-dropdown"
INTERNET_SERVICE_TYPE = "p-dropdownitem:nth-of-type(1)"
PASSWORD = "#login-password-et"
SIGN_IN_BUTTON = "#login-login-btn"
DAYS_LEFT = "small"
CONSUMED_UNITS = ".usage-details"
REMAINING_UNITS = ".remaining-details"
