SERVICE_NUMBER = "#login-service-number-et"
SERVICE_TYPE = "p-dropdown.ng-tns-c82-6"
INTERNET_SERVICE_TYPE = "p-dropdownitem.ng-tns-c82-6:nth-child(1)"
PASSWORD = "#login-password-et"
SIGN_IN_BUTTON = "#login-login-btn"
DAYS_LEFT = ".mr-auto"
CONSUMED_UNITS = ".usage-details"
REMAINING_UNITS = ".remaining-details"
